private_jimyou/jimyou/urls.py
from django.urls import path
from . import views

app_name = 'jimyou'
urlpatterns = [
    path('', views.home_view, name="index"),
    path('home-page/', views.HomeView.as_view(), name="home-page"),
    path('services/', views.profile, name="services"),
    path('about-us/', views.AboutusView.as_view(), name="about-us"),
    path('about-me/', views.AboutmeView.as_view(), name="about-me"),
    path('contacts/', views.add, name="contacts"),
    path('hm/', views.HmView.as_view(), name="hm"),
    path('index-account/', views.Account_login.as_view(), name="index-account"),

]

private_jimyou/private_jimyou/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('jimyou.urls')),
    path("accounts/",include('accounts.urls'))
]

private_jimyou/jimyou/models.py
# https://zenn.dev/shimakaze_soft/articles/7f3a12881614b5
from django.db import models
from accounts.models import Usertest


class Profiletest(models.Model):
    user = models.ForeignKey(Usertest,verbose_name='ユーザー',on_delete=models.PROTECT)
    limit = models.DateField(verbose_name='目標達成日',null=True, blank=True)
    title = models.CharField(verbose_name='目標の名前',max_length=30, blank=True)
    text = models.CharField(verbose_name='目標の説明',max_length=50, blank=True)
    text1 = models.CharField(verbose_name='目標の説明',max_length=50, blank=True)
    text2 = models.CharField(verbose_name='目標の説明',max_length=50, blank=True)
    text3 = models.CharField(verbose_name='目標の説明',max_length=50, blank=True)

    # class Meta:
    #     verbose_name_plural = 'Profile'
    # def __str__(self):
    #     return self.gender

# https://di-acc2.com/programming/python/1694/
class Profilet(models.Model):
    user = models.ForeignKey(Usertest,verbose_name='ユーザー',on_delete=models.PROTECT)
    limit = models.DateField(verbose_name='目標達成日',null=True, blank=True)
    title = models.CharField(verbose_name='目標の名前',max_length=30, blank=True)
    text = models.CharField(verbose_name='目標の説明',max_length=150, blank=True)
    check = models.BooleanField(verbose_name='完了/未完了')

private_jimyou/jimyou/forms.py
import os

from django import forms
from django.core.mail import EmailMessage
from accounts.models import Usertest
from .models import Profilet
class CreateForm(forms.ModelForm):
    class Meta:
        model = Profilet
        fields = ('user', 'limit', 'title', 'text','check')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

#from django import forms
# https://hombre-nuevo.com/python/python0038/
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import Usertest,Profiletest
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       #htmlの表示を変更可能にします
       self.fields['username'].widget.attrs['class'] = 'form-control'
       self.fields['password'].widget.attrs['class'] = 'form-control'

class UserCreateForm(UserCreationForm):
    birthday = forms.CharField(required=True)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['birthday'].widget.attrs['class'] = 'form-control'
        self.fields['country'].widget.attrs['class'] = 'form-control'
        self.fields['gender'].widget.attrs['class'] = 'form-control'

    class Meta:
       model = Usertest
       fields = ("username", "password1", "password2","birthday","country","gender")

class UserUpdateForm(forms.ModelForm):
 
    # 入力を必須にするために、required=Trueで上書き
    birthday = forms.CharField(required=True)
    email = forms.EmailField(max_length=30, required=True)
    userver = forms.CharField(max_length=30, required=True)
 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = kwargs.get('instance', None)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['birthday'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['userver'].widget.attrs['class'] = 'form-control'
 
    class Meta:
        model = User
        fields = (
            "username", "birthday", "email", "userver",
        )
 
    def clean_email(self):
        email = self.cleaned_data["email"]
 
        try:
            validate_email(email)
        except ValidationError:
            raise ValidationError("正しいメールアドレスを指定してください。")
 
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        else:
            if self.user.email == email:
                return email
 
            raise ValidationError("このメールアドレスは既に使用されています。別のメールアドレスを指定してください")
 
class UserPasswordChangeForm(PasswordChangeForm):
    pass


class ProfileCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].widget.attrs['class'] = 'form-control'
        self.fields['limit'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['text'].widget.attrs['class'] = 'form-control'
        self.fields['text1'].widget.attrs['class'] = 'form-control'

    class Meta:
       model = Profiletest
       fields = ("user","limit", "title","text","text1")

private_jimyou/jimyou/views.py
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, redirect
from jimyou.models import Profiletest,Usertest,Profilet
from jimyou.forms import CreateForm
import datetime
class BaseView(generic.TemplateView):
    template_name = "base.html"
    
    


class IndexView(generic.TemplateView):
    template_name = "index.html"
    def birthday(request,year, month, day):
        Birthday = Usertest.objects.get(test='birthday')
        today = datetime.date.today()
        birthday = datetime.date(Usertest.objects.get(test='birthday'))
        context = {'Birthday':Birthday, }
        return (int(today.strftime("%Y%m%d")) - int(birthday.strftime("%Y%m%d"))) // 10000

class HomeView(generic.TemplateView):
    template_name = "home-page.html"

class AboutusView(generic.TemplateView):
    template_name = "about-us.html"

class AboutmeView(generic.TemplateView):
    template_name = "about-me.html"

class ContactsView(generic.TemplateView):
    template_name = "contacts.html"

def add(request):
    """
    日記の記事を追加
    """
    # 送信内容を元にフォームを作る。POSTじゃなければ空のフォームを作成。
    form = CreateForm(request.POST or None)

    # method==POSTとは送信ボタンが押されたとき。form.is_validは入力内容に問題が無い場合Trueになる。
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('../../')

    # 通常時のアクセスや入力内容に誤りがあれば、再度day_form.htmlを表示
    context = {
        'form':form
    }
    return render(request, 'contacts.html', context)

class HmView(generic.TemplateView):
    template_name = "hm.html"

class GurafuView(generic.TemplateView):
    template_name = "gurafu.html"

from .forms import CreateForm
def home_view(request):
    context = {}
    context['form'] = CreateForm()
    return render(request, 'index.html', context)



def profile(request):
    """
    日記の一覧
    """
    context = {
        'profile_list':Profilet.objects.all(),
    }
    return render(request, 'services.html', context)

from django.views import View
from jimyou.forms import LoginForm
from django.contrib.auth import login
class Account_login(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = Usertest.objects.get(username=username)
            login(request, user)
            return redirect('/')
        return render(request, 'index-account.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'index-account.html', {'form': form,})

private_jimyou/jimyou/templates/base.html
{% load static %}

<html lang="ja">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="keywords" content="Bootstrap Theme, Freebies, UI Kit, MIT license">
    <meta name="description" content="Stream - Bootstrap 4 UI Kit">
    <meta name="author" content="htmlstream.com">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static '/assets/favicon.ico'%}"/>

    <!-- Web Fonts -->
    <link href="//fonts.googleapis.com/css?family=Playfair+Display:400,700%7COpen+Sans:300,400,600,700" rel="stylesheet">

    <!-- Bootstrap Styles -->
    <link rel="stylesheet" type="text/css" href="{% static '/assets/vendors/bootstrap/css/bootstrap.min.css'%}"/>
    <!-- Components Vendor Styles -->
    <link rel="stylesheet" type="text/css" href="{% static '/assets/vendors/font-awesome/css/fontawesome-all.min.css'%}"/>
    <!-- Theme Styles -->
    <link rel="stylesheet" type="text/css" href="{% static '/assets/css/styles.css'%}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/flip-master/example/flip/flip.min.css'%}"/>

    <!-- My styles -->


    

    <!-- Demo Custome Code (demo page only) -->
    <style type="text/css">
      /* Button Spaces*/
      .demo-btn-space .btn,
      .demo-progress-space .progress {
        margin-bottom: 10px;
      }
      /* About Section */
      .demo-about-section {
        position: relative;
        padding-top: 6.25rem;
      }
      @media (min-width: 991px) {
        .demo-about-section {
          margin-top: -50px;
          padding-top: 0;
        }
      }
      /* Download Section */
      .demo-download-section {
        position: relative;
        z-index: 1;
        margin: -60px 0;
      }
      /* Google Fonts */
      .demo-fonts-box {
        padding: 30px;
        line-height: 2;
        letter-spacing: 2px;
      }
      .demo-fonts-box__item {
        line-height: 1;
      }
      .demo-fonts-box__item-xs {
        line-height: 1;
        font-size: 30px;
      }
      .demo-fonts-box__item-xl {
        line-height: 1;
        font-size: 90px;
      }
    </style>
    {% block head %}{% endblock %}
  </head>

    <body>
      <nav class="js-navbar-scroll navbar fixed-top navbar-expand-lg navbar-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'jimyou:home-page' %}">
            <img src="{% static '/assets/img/logo-white.png' %}" alt="Stream UI Kit" style="width: 100px;">
          </a>
    
          <button class="navbar-toggler" type="button"
                  data-toggle="collapse"
                  data-target="#navbarTogglerDemo"
    
                  aria-controls="navbarTogglerDemo"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="collapse navbar-collapse" id="navbarTogglerDemo">
            <ul class="navbar-nav mt-2 mt-lg-0">
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link active" href="/">戻る</a>
              </li>
            </ul>
    
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link active" href="{% url 'jimyou:index' %}">ホーム</a>
              </li>
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="{% url 'jimyou:services' %}">夢：目標一覧</a>
              </li>
              <li class="nav-item dropdown mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  仮設1 <i class="fas fa-angle-down small ml-1"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'jimyou:about-us' %}">仮設1</a>
                  <a class="dropdown-item" href="{% url 'jimyou:about-me' %}">仮設1</a>
                </div>
              </li>
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="{% url 'jimyou:contacts' %}">夢：目標登録</a>
              </li>
    
              <!-- 付け足し -->
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="{% url 'jimyou:hm' %}">濱頭グラフ</a>
              </li>
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                <a class="nav-link" href="{% url 'jimyou:index-account' %}">アカウント</a>
              </li>
              <li class="nav-item mr-4 mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout' %}">サインアウト</a>
                {% else %}
                <a class="nav-link" href="{% url 'login' %}">ログイン</a>
                {% endif %}
              </li>
              <!-- ここまで -->
              
            </ul>
            <div>
            </div>
          </div>
        </div>
      </nav>
    {% block section %}{% endblock %}
    {% block contents%}{% endblock %}
    <script type="text/javascript" src="{% static '/assets/vendors/jquery.min.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/vendors/jquery.migrate.min.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/vendors/popper.min.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/vendors/bootstrap/js/bootstrap.min.js'%}"></script>

    <!-- Components Vendor  -->
    <script type="text/javascript" src="{% static '/assets/vendors/jquery.parallax.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/vendors/typedjs/typed.min.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/vendors/slick-carousel/slick.min.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/vendors/counters/waypoint.min.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/vendors/counters/counterup.min.js'%}"></script>

    <!-- Theme Settings and Calls -->
    <script type="text/javascript" src="{% static '/assets/js/global.js'%}"></script>

    <!-- Theme Components and Settings -->
    <script type="text/javascript" src="{% static '/assets/js/vendors/parallax.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/js/vendors/carousel.js'%}"></script>
    <script type="text/javascript" src="{% static '/assets/js/vendors/counters.js'%}"></script>
    <!-- END JAVASCRIPTS -->
</body>
</html>

private_jimyou/jimyou/templates/contacts.html
{% extends 'base.html' %}
{% load static %}

{% block header %}{% endblock %}
{% block section %}
      <section class="js-parallax u-promo-block u-promo-block--mheight-500 u-overlay u-overlay--dark text-white" style="background-image: url(../../static/assets/img-temp/1920x1080/img12.jpg);">
        <!-- Promo Content -->
        <div class="container u-overlay__inner u-ver-center u-content-space">
          <div class="row justify-content-center">
            <div class="col-12">
              <div class="text-center">
                <h1 class="display-sm-4 display-lg-3">目標登録画面</h1>
                <p class="h6 text-uppercase u-letter-spacing-sm mb-0">テスト</p>
              </div>
            </div>
          </div>
        </div>
        <!-- End Promo Content -->
      </section>
      <!-- End Promo Block -->
    </header>
    <!-- End Header -->
    {% endblock %}
    {% block contents %}
      <!-- Contact Form -->
      <section class="u-content-space">
        <div class="container">
          <header class="text-center w-md-50 mx-auto mb-8">
            <h2 class="h1">テスト</h2>
            <p class="h5">テスト</p>
          </header>
          <form action="" method="POST">
            {% csrf_token %}
            <table class="tabel">
                <label>ユーザーID</label>
                <div class="col-lg-6 form-group mb-4">{{ form.user }}{{ form.user.errors }}</div>
                <label>夢：目標の達成日</label>
                <div class="col-lg-6 form-group mb-4">{{ form.limit }}{{ form.limit.errors }}</div>
                <label>夢：目標の名前</label>
                <div class="col-lg-6 form-group mb-4">{{ form.title }}{{ form.title.errors }}</div>
                <label>夢：目標の説明</label>
                <div class="col-lg-12 form-group mb-6">{{ form.text }}{{ form.text.errors }}</div>
            </table>
            <div class="text-center">
              <button class="btn btn-lg btn-primary py-3 px-4" type="submit">登録</button>
            </div>
          </form>
        </div>
      </section>
      <!-- End Contact Form -->
    </main>

    <!-- Footer -->
    <footer class="bg-dark py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-8 text-center text-md-left mb-3 mb-md-0">
            <small class="text-white">&copy; 2018 <a class="text-white" href="https://htmlstream.com">Htmlstream</a>. All Rights Reserved.</small>
          </div>

          <div class="col-md-4 align-self-center">
            <ul class="list-inline text-center text-md-right mb-0">
              <li class="list-inline-item mx-2" data-toggle="tooltip" data-placement="top" title="Facebook">
                <a class="text-white" target="_blank" href="https://www.facebook.com/htmlstream">
                  <i class="fab fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item mx-2" data-toggle="tooltip" data-placement="top" title="Instagram">
                <a class="text-white" target="_blank" href="https://www.instagram.com/htmlstream">
                  <i class="fab fa-instagram"></i>
                </a>
              </li>
              <li class="list-inline-item mx-2" data-toggle="tooltip" data-placement="top" title="Twitter">
                <a class="text-white" target="_blank" href="https://twitter.com/htmlstream">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item mx-2" data-toggle="tooltip" data-placement="top" title="Dribbble">
                <a class="text-white" target="_blank" href="https://dribbble.com/htmlstream">
                  <i class="fab fa-dribbble"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!-- End Footer -->

    <!-- Call Us Modal Window -->
    <div class="modal fade" id="callUsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <form action="#">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">We'll call you</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="form-group mb-4">
                <input type="text" class="form-control" id="modalName" placeholder="Your Name">
              </div>
              <div class="form-group mb-4">
                <input type="tel" class="form-control" id="modalPhone" placeholder="Your Phone Number">
              </div>
              <div class="text-right">
                <button type="submit" class="btn btn-primary">Send</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- End Call Us Modal Window -->

    <!-- JAVASCRIPTS (Load javascripts at bottom, this will reduce page load time) -->
    <!-- Global Vendor -->
    <script src="{% static '/assets/vendors/jquery.min.js' %}"></script>
    <script src="{% static '/assets/vendors/jquery.migrate.min.js' %}"></script>
    <script src="{% static '/assets/vendors/popper.min.js' %}"></script>
    <script src="{% static '/assets/vendors/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Components Vendor  -->
    <script src="{% static '/assets/vendors/jquery.parallax.js' %}"></script>

    <!-- Theme Settings and Calls -->
    <script src="{% static '/assets/js/global.js' %}"></script>

    <!-- Theme Components and Settings -->
    <script src="{% static '/assets/js/vendors/parallax.js' %}"></script>
    <!-- END JAVASCRIPTS -->
  </body>
  {% endblock %}
  <!-- End Body -->
</html>

private_jimyou/jimyou/templates/gurafu.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
</head>
<body>
    <!-- chart.js -->
    <canvas id="myChart"></canvas>

    <script>

        var ctx = document.getElementById('myChart').getContext('2d');
        var chart = new Chart(ctx, {
            // The type of chart we want to create
            type: 'line',

            // The data for our dataset
            data: {
                labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
                datasets: [{
                    label: 'My First dataset',
                    backgroundColor: 'rgb(255, 99, 132)',
                    borderColor: 'rgb(255, 99, 132)',
                    data: [0, 10, 5, 2, 20, 30, 45]
                }]
            },

            // Configuration options go here
            options: {}
        });

    </script>
</body>
</html>

private_jimyou/jimyou/templates/home-page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home Page{% endblock %}
{% block header %}{% endblock %}
{% block section %}
<section class="js-parallax u-promo-block u-promo-block--mheight-500 u-overlay u-overlay--dark text-white" style="background-image: url(../../static/assets/img-temp/1920x1080/2.png);">
  <div class="container u-overlay__inner u-ver-center u-content-space">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="text-center">
          <h1 class="display-sm-4 display-lg-3">プロジェクト名</h1>
          <p class="h6 text-uppercase u-letter-spacing-sm mb-0">テストテスト</p>
        </div>
      </div>
    </div>
  </div>
</section>{% endblock %}

{% block contents %}
<section class="bg-light u-content-space">
  <div class="container">
    <!-- Feature Blocks -->
    <div class="row">
      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fab fa-grav"></i>
        </div>
        <a h4 class="h5" href="https://www.mhlw.go.jp/toukei/saikin/hw/life/life21/index.html">日本の平均寿命</h4>
        <p></p>
      </div>

      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fab fa-connectdevelop"></i>
        </div>
        <a h4 class="h5" href="https://www.bing.com/search?q=%E4%BA%BA%E7%94%9F%E8%A8%AD%E8%A8%88&qs=n&form=QBRE&msbsrank=10_11__0&sp=-1&pq=%E4%BA%BA%E7%94%9F%E8%A8%AD%E8%A8%88&sc=11-4&sk=&cvid=209D07485D394D738F569544160AAC05&ghsh=0&ghacc=0&ghpl=">目標・人生設計のアシスト</h4>
        <p></p>
      </div>

      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fas fa-cubes"></i>
        </div>
        <a h4 class="h5" href="">このサイトを作った理由</h4>
        <p>アカウントの編集をします</p>
      </div>
    </div>
  </div>
</section>{% endblock %}

private_jimyou/jimyou/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home Page{% endblock %}
{% block header %}{% endblock %}
{% block section %}
<section class="js-parallax u-promo-block u-promo-block--mheight-500 u-overlay u-overlay--dark text-white" style="background-image: url(../../static/assets/img-temp/1920x1080/img8.jpg);">
  <div class="container u-overlay__inner u-ver-center u-content-space">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="text-center">
          <h1 class="display-sm-4 display-lg-3">{{user.birthday}}</h1>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{% block contents %}
<section class="bg-light u-content-space">
  <div class="container">
    <!-- <header class="text-center w-md-50 mx-auto mb-8">
      <h2 class="h1">Features</h2>
      <p class="h5">We help everyone achieve their dreams and goals</p>
    </header> -->

    <!-- Feature Blocks -->
    <div class="row">
      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fab fa-grav"></i>
        </div>
        <a h4 class="h5" href="{% url 'create_account' %}">Account create</h4>
        <p></p>
      </div>

      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fab fa-connectdevelop"></i>
        </div>
        <a h4 class="h5" href="{% url 'login' %}">Account login</h4>
        <p></p>
      </div>

      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fas fa-cubes"></i>
        </div>
        <a h4 class="h5" href="{% url 'update_account' %}">Account update</h4>
        <p>アカウントの編集をします</p>
      </div>
    </div>
    <!-- End Feature Blocks -->

    <hr class="my-8">

    <!-- Feature Blocks -->
    <div class="row">
      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fab fa-vuejs"></i>
        </div>
        <a h4 class="h5" href="{% url 'jimyou:contacts' %}">dream create</h4>
        <p>夢の登録をします</p>
      </div>

      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fab fa-react"></i>
        </div>
        <a h4 class="h5" href="{% url 'jimyou:services' %}">dream list</h4>
        <p>夢の一覧を表示します</p>
      </div>

      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="display-4 text-primary mb-2">
          <i class="fab fa-angular"></i>
        </div>
        <a h4 class="h5" href="{% url 'create_profile' %}">登録</h4>
        <p>登録の仕方について説明します</p>
      </div>
    </div>
    <!-- End Feature Blocks -->
  </div>
</section>
<a href="{% url 'create_profile' %}">目標作成</a>
{% endblock %}